name: Checkout Example
on: 
  workflow_dispatch:

jobs:
  checkout-example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.1
      - name: verification
        run: ls -alhR
      
